[versions]
activityCompose = "1.11.0" # https://developer.android.com/jetpack/androidx/releases/activity#1.11.0
agp = "8.13.1" # https://developer.android.com/build/releases/gradle-plugin
androidx-navigation = "2.9.6" # https://developer.android.com/jetpack/androidx/releases/navigation
androidx-test-espresso = "3.7.0" # https://developer.android.com/jetpack/androidx/releases/test#espresso-3.7.0
androidx-test-ext-junit = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/test#junit_extensions_130_2
androidx-test-orchestrator = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/test#orchestrator-1.6.1
androidx-test-rules = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test#rules-1.7.0
androidx-test-runner = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test#runner-1.7.0
compose-lint-rules = "0.4.27" # https://github.com/mrmans0n/compose-rules/releases/
composeBom = "2025.11.00" # https://developer.android.com/jetpack/androidx/releases/compose
coreKtx = "1.17.0" # https://developer.android.com/jetpack/androidx/releases/core#1.17.0
detekt = "1.23.8" # https://github.com/detekt/detekt/releases
espressoCore = "3.7.0" # https://developer.android.com/jetpack/androidx/releases/test#3.7.0
jackson = "3.0.2" # https://github.com/FasterXML/jackson/wiki/Jackson-Releases
jacoco = "0.8.14" # https://github.com/jacoco/jacoco/releases
junit = "4.13.2" # https://github.com/junit-team/junit4/releases
kotlin = "2.2.21" # https://github.com/JetBrains/kotlin/releases
kotlin-symbol-processing = "2.3.2" # https://github.com/google/ksp/releases ; update with 'kotlin'
kotlinx-collections-immutable = "0.4.0" # https://github.com/Kotlin/kotlinx.collections.immutable/releases
ktlint = "1.7.1" # https://github.com/pinterest/ktlint/releases/
lifecycle = "2.10.0" # https://developer.android.com/jetpack/androidx/releases/lifecycle#2.9.4
mockk = "1.14.6" # https://github.com/mockk/mockk/releases
robolectric = "4.16" # https://github.com/robolectric/robolectric/releases
roborazzi = "1.51.0" # https://github.com/takahirom/roborazzi/releases
sonarqube = "7.0.1.6134" # https://github.com/SonarSource/sonar-scanner-gradle/releases
spotless = "8.0.0" # https://github.com/diffplug/spotless/releases?q=%22Gradle+Plugin%22
turbine = "1.2.1" # https://github.com/cashapp/turbine/releases
uk-gov-ui = "10.0.0" # https://github.com/govuk-one-login/mobile-android-ui/tags
xzing = "3.5.4" # Changelog https://github.com/zxing/zxing/releases

[libraries]
app-cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
com-google-devtools-ksp-gradle = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "kotlin-symbol-processing" }
compose-rules-detekt = { module = "io.nlopez.compose.rules:detekt", version.ref = "compose-lint-rules" }
compose-rules-ktlint = { module = "io.nlopez.compose.rules:ktlint", version.ref = "compose-lint-rules" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
jackson-cbor = { module = "tools.jackson.dataformat:jackson-dataformat-cbor", version.ref = "jackson" }
jackson-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
org-jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
org-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
roborazzi-gradle = { module = "io.github.takahirom.roborazzi:roborazzi-gradle-plugin", version.ref = "roborazzi" }
roborazzi-rule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
sonarqube-gradle = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqube" }
spotless-gradle = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
uk-gov-pipelines-plugins = { module = "uk.gov.pipelines:plugins" }
uk-gov-ui-android-componentsv2 = { module = "uk.gov.android:componentsv2", version.ref = "uk-gov-ui" }
uk-gov-ui-android-componentsv2-camera = { module = "uk.gov.android:componentsv2-camera", version.ref = "uk-gov-ui" }
uk-gov-ui-android-patterns = { module = "uk.gov.android:patterns", version.ref = "uk-gov-ui" }
uk-gov-ui-android-patterns-camera = { module = "uk.gov.android:patterns-camera", version.ref = "uk-gov-ui" }
uk-gov-ui-android-theme = { module = "uk.gov.android:theme", version.ref = "uk-gov-ui" }
zxing-core = { module = "com.google.zxing:core", version.ref = "xzing" }

[bundles]
android-baseline = [
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-material3",
    "androidx-navigation-compose",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "kotlinx-collections-immutable"
]
debug-tooling = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest",
]
testing-instrumentation = [
    "androidx-espresso-core",
    "androidx-junit",
    "androidx-test-rules",
    "androidx-ui-test-junit4",
]
testing-unit = [
    "junit",
    "androidx-navigation-testing",
    "androidx-test-espresso-intents",
    "androidx-test-rules",
    "androidx-ui-test-junit4",
    "app-cash-turbine",
    "kotlin-test",
    "mockk",
    "org-robolectric",
]
screenshot-testing = [
    "junit",
    "org-robolectric",
    "roborazzi",
    "roborazzi-compose",
    "roborazzi-rule",
]
uk-gov-ui = [
    "uk-gov-ui-android-componentsv2",
    "uk-gov-ui-android-componentsv2-camera",
    "uk-gov-ui-android-patterns",
    "uk-gov-ui-android-patterns-camera",
    "uk-gov-ui-android-theme",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint-config = { id = "uk.gov.onelogin.sharing.plugins.lint.android-configuration", version = "undefined" }
custom-language-config = { id = "uk.gov.onelogin.sharing.plugins.language.language-configuration", version = "undefined" }
custom-managed-devices = { id = "uk.gov.onelogin.sharing.plugins.devices.gradle-managed-devices", version = "undefined" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
detekt-config = { id = "uk.gov.onelogin.sharing.plugins.lint.detekt-configuration", version = "undefined" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
screenshot-testing = { id = "uk.gov.onelogin.sharing.plugins.testing.android-screenshot-testing", version = "undefined" }
sonar-module-config = { id = "uk.gov.onelogin.sharing.plugins.sonar.sub-module-config", version = "undefined" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotless-config = { id = "uk.gov.onelogin.sharing.plugins.lint.spotless-configuration", version = "undefined" }
templates-android-library = { id = "uk.gov.onelogin.sharing.plugins.android-library-template", version = "undefined" }
templates-kotlin-library = { id = "uk.gov.onelogin.sharing.plugins.kotlin-library-template", version = "undefined" }
test-coverage = { id = "uk.gov.onelogin.sharing.plugins.testing.test-coverage", version = "undefined" }
