name: Release mobile-credential-sharing-android

on:
  push:
    branches: [ "main", "dcmaw-16161-google-play-deployment" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Free disk space
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Install linux packages
        run: |
          ./scripts/installLinuxPackages

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner
        with:
          gradle-cache-disabled: "false"
          jdk-version: "21"

      - name: Install homebrew packages
        run: |
          brew bundle

      - name: Verify Conventional commit standards against latest git tag
        run: cog check -l
        shell: bash

      - name: Run linting suites
        run: |
          ./scripts/lint/all

      - name: Run testing suites
        run: |
          ./scripts/test/all

      - name: Calculate version increment
        id: calc-version
        uses: ./mobile-android-pipelines/actions/increment-version
        with:
          dry-run: true

      - name: Sonar scan
        uses: ./mobile-android-pipelines/actions/sonar-scan
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          version-name: ${{ github.ref == 'refs/heads/main' && steps.calc-version.outputs.new_version }}

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

  bump_and_publish:
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner
        with:
          gradle-cache-disabled: "false"
          jdk-version: "21"

      - name: Install homebrew packages
        run: |
          brew bundle

      - name: Increment the release version using Conventional Commits
        id: versioning
        uses: ./mobile-android-pipelines/actions/increment-version

      - name: Publish release tags
        if: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        uses: ./mobile-android-pipelines/actions/publish-release-tag

      - name: Publish package
        if: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        uses: ./mobile-android-pipelines/actions/maven-publish
        with:
          VERSION_NAME: ${{ steps.versioning.outputs.new_version }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Generate Changelog
        if: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        uses: ./mobile-android-pipelines/actions/generate-and-upload-changelog
        with:
          current-version: ${{ steps.versioning.outputs.current_version }}
          new-version: ${{ steps.versioning.outputs.new_version }}
          version-prefix: "v"

      - name: Retrieve Secrets
        id: secrets
        uses: ./mobile-android-pipelines/actions/retrieve-secrets
        with:
          keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
          # No service account needed as we are using Workload Identity Federation
          google-service-account-json-base64: ""

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        id: auth
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/deploy-credential-sharing-and/providers/github-actions
          service_account: deploy-credential-sharing-and@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Bundle Demo Release
        if: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        id: bundle
        uses: ./mobile-android-pipelines/actions/bundle-release-app
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          keystore-file-path: ${{ steps.secrets.outputs.keystore-file-path }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          keystore-key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          keystore-key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD}}
          version-code: ${{ steps.versioning.outputs.version-code }}

      - name: Publish to Play Store
        if: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        uses: ./actions/publish-to-play-store
        with:
          aab-paths: ${{ steps.bundle.outputs.aab-paths }}
          package-name: 'uk.gov.onelogin.sharing'
          google-service-account-json: ${{ steps.auth.outputs.credentials_file_path }}
          track: 'internal'

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

